export { default as KYCForm } from './KYCForm'
export { default as PersonalDetailsForm } from './PersonalDetailsForm'
export { default as PhotoIDsForm } from './PhotoIDsForm'
export { default as PrimaryAddressForm } from './PrimaryAddressForm'
export { default as AddPaymentMethodForm } from './AddPaymentMethodForm'
export { default as WebCamModal } from './WebCamModal'
