apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cex
  namespace: lux-cex
  labels:
    app: cex
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cex.lux.network`)
      kind: Rule
      services:
        - name: cex
          port: 8091
  tls:
    certResolver: letsencrypt
