apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lux-cex

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: lux
  app.kubernetes.io/component: cex
